### PR TITLE
Bag with more then one CKEditor textareas

### PR DESCRIPTION
**Pull request by RomanMinkin**
1. Fixed issue with more than one CKEditor fields in document. Before dialogs did insert html with embeded media only in one editor textarea.
2. Added toolbar setting for ui button

### CODE REVIEW

**Comment by frozeman** [comment]
thanks for that. did you test it?

i uploaded your patched version to the ckeditor website

**Comment by RomanMinkin** [comment]
Hi,

Yes I did test with 4.x version.
I'm using multiple textareas in one page, it's why i did fix =)

Is' better to use editor instance on dialog initialization that editor itself

``` javascript
         init: function( editor )
         {
            var me = this;  
-           CKEDITOR.dialog.add( 'MediaEmbedDialog', function ()
+           CKEDITOR.dialog.add( 'MediaEmbedDialog', function (instance)
...

+                    instance.insertHtml(this.getContentElement( 'iframe', 'embedArea' ).getValue());
...
            {
```

**Comment by frozeman** [comment]
absolutely right, thanks man.

**Comment by RomanMinkin** [comment]
Any time!

On Fri, Jan 25, 2013 at 3:38 PM, Fabian Vogelsteller <
notifications@github.com> wrote:

> absolutely right, thanks man.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/frozeman/MediaEmbed/pull/1#issuecomment-12719627.

## 

Best regards,

Roman Minkin

**Pull request merged**
